@component('mail::message')
# New Incident: {{ $incident->title }}

A new incident was posted to the Repository by {{ $incident->user->name }} 
on {{ \Carbon\Carbon::parse($incident->created_at)->toFormattedDateString() }} 
at {{ \Carbon\Carbon::parse($incident->created_at)->format('g:i:s A') }}.

@component('mail::button', ['url' => url('incidents', [$incident->id])])
View Incident
@endcomponent

Thanks,<br>
{{ config('app.name') }}

@component('mail::panel')
Please do not reply to this email; it has been dynamically generated by the LPL Repository 
and the mailbox it was sent from is not monitored.
If you need assistance or have a question, please email LibraryTechnologyandInnovation@cityofloveland.org.
@endcomponent

@endcomponent
