version: '2'
services:
 app:
  depends_on:
   - db
  image: redisforlosers/repository
  volumes:
   - ./:/repository
  ports:
   - 10000:10000
  container_name: repository
  hostname: repository

 phpmyadmin:
  depends_on:
   - db
  image: phpmyadmin/phpmyadmin
  ports:
   - 8888:80
  container_name: phpmyadmin-repository
  hostname: phpmyadmin-repository

 db:
  image: mysql:5.7
  volumes:
   - dbdata:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: lpl_repository_root
   MYSQL_DATABASE: dev_repository
   MYSQL_USER: lpl_repository
   MYSQL_PASSWORD: lpl_repository
  ports:
   - 3307:3306
  container_name: mysql-repository
  hostname: mysql-repository

volumes:
  dbdata: