version: '2'
services:
 app:
  depends_on:
   - db
  build:
    context: ./docker
  image: redisforlosers/hub
  volumes:
   - ./src/:/hub
  ports:
   - 10000:10000
  container_name: hub
  hostname: hub

 composer:
  image: composer
  volumes:
    - ./src/:/hub/
  working_dir: /hub/
  command: ["composer", "install"]
  container_name: hub-composer
  hostname: hub-composer

 phpmyadmin:
  depends_on:
   - db
  image: phpmyadmin/phpmyadmin
  ports:
   - 18888:80
  container_name: hub-phpmyadmin
  hostname: hub-phpmyadmin

 db:
  image: mysql:5.7
  volumes:
   - dbdata:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: lpl_hub_root
   MYSQL_DATABASE: dev_hub
   MYSQL_USER: lpl_hub
   MYSQL_PASSWORD: lpl_hub
  ports:
   - 13306:3306
  container_name: hub-mysql
  hostname: hub-mysql

volumes:
  dbdata: