version: '2'
services:
 app:
  depends_on:
   - db
  image: redisforlosers/lpl_wiki
  volumes:
   - ./:/app
  ports:
   - 10000:10000
  container_name: wiki

 phpmyadmin:
  depends_on:
   - db
  image: phpmyadmin/phpmyadmin
  ports:
   - 8888:80
  container_name: phpmyadmin-wiki

 db:
  image: mysql:5.7
  volumes:
   - ./database/.dbdata:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: lpl_wiki_root
   MYSQL_DATABASE: dev_wiki
  ports:
   - 3307:3306
  container_name: mysql-wiki