@component('mail::message')
# Incident Updated - {{ $incident->title }}

An incident you created was updated by {{ App\User::find($incident->updated_by)->name }} 
on {{ \Carbon\Carbon::parse($incident->updated_at)->toFormattedDateString() }} 
at {{ \Carbon\Carbon::parse($incident->updated_at)->format('h:i:s A') }}.

@component('mail::button', ['url' => url('incidents', [$incident->id])])
Click here to view the incident
@endcomponent

Thanks,<br>
{{ config('app.name') }}

@component('mail::panel')
Please do not reply to this email; it has been dynamically generated by the LPL Repository 
and the mailbox it was sent from is not monitored.
If you need assistance or have a question, please email kevin.briggs@cityofloveland.org.
@endcomponent

@endcomponent