@component('mail::message')
# New Incident

A new incident as been posted to the Repository by {{ $incident->user->name }}.

@component('mail::button', ['url' => url('incidents', [$incident->id])])
View Incident
@endcomponent

Thanks,<br>
{{ config('app.name') }}

@component('mail::panel')
Please do not reply to this email; it has been dynamically generated by the LPL Repository 
and the mailbox it was sent from is not monitored.
If you need assistance or have a question, please email kevin.briggs@cityofloveland.org.
@endcomponent

@endcomponent
